declare module "@git-validator/eslint-plugin" {}
declare module "eslint-plugin-fp" {}
declare module "eslint-plugin-import" {}
declare module "eslint-plugin-n" {}
declare module "eslint-plugin-promise" {}
declare module "eslint-plugin-simple-import-sort" {}
declare module "eslint-plugin-unicorn" {}
declare module "eslint-plugin-react-hooks" {}
declare module "eslint-config-prettier" {}
